# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skillslogo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='skillslogo/'),
            preserve_default=False,
        ),
    ]
